type User @table {
  displayName: String!
  email: String!
  userType: String!
  phoneNumber: String
  address: String
  photoUrl: String
}

type Service @table {
  name: String!
  description: String!
  basePrice: Float!
  imageUrl: String
  estimatedDuration: Int
}

type ProviderService @table {
  user: User!
  service: Service!
  customDescription: String
  customPrice: Float
}

type Availability @table {
  provider: User!
  startTime: Timestamp!
  endTime: Timestamp!
  isBooked: Boolean!
  service: Service
}

type Booking @table {
  customer: User!
  providerService: ProviderService!
  availability: Availability!
  bookingTime: Timestamp!
  status: String!
  specialInstructions: String
  totalCost: Float
}